### PR TITLE
Fix size of complete undirected graphs

### LINKED ISSUE #89: Fix: default size of complete undirected graph
### What happened?

The default size of a complete undirected graph with _n_ labels is set for default to `(n * (n+1)) / 2`, while it must be set to `n * (n+1) / 2 - n`. Indeed this quantity is equivalent to `(n * (n -1)) / 2`, but it prevents the code to overflow in case of `n = 0`, with `n` being of type `usize`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Niccolo-Rocchi**
# Description

_Fix default size in creation of complete undirected graphs._

_Add the issue reference number:_ #89 

Fixes #89 

## Pull Request Type

Choose the pull request type:

- [x] Bug Fix,
- [ ] Feature Addition,
- [ ] Other: _Add brief description_.

## Pull Request Checklist

Make sure that the following checklist is satisfied:

- [x] Pull request branch is `develop`,
- [x] Pull request description is written,
- [x] `Fixes #(ISSUE)` number is set,
- [x] `CONTRIBUTING` guidelines are satisfied:
  - [x] Build do not fail,
  - [x] Tests do not fail,
  - [x] Coverage is adequate,
  - [x] Code is properly linted,
  - [x] Code is properly formatted,
  - [x] Code is properly documented.

### CODE REVIEW

File: src/graphs/structs/undirected_dense_adjacency_matrix.rs [hunk 1]
```diff
@@ -628,7 +628,7 @@ impl DefaultGraph for UndirectedDenseAdjacencyMatrixGraph {
         adjacency_matrix.diag_mut().map_inplace(|x| *x = false);
 
         // Compute size.
-        let size = (order * (order + 1)) / 2;
+        let size = (order * (order + 1)) / 2 - order;
```
Comment (AlessioZanga) [inline src/graphs/structs/undirected_dense_adjacency_matrix.rs:631]: We can stick to the `(n * (n - 1)) / 2` formula and avoiding underflow by using [saturating_sub](https://doc.rust-lang.org/std/primitive.usize.html#method.saturating_sub).

File: tests/graphs/default.rs [hunk 2]
```diff
@@ -106,7 +106,7 @@ mod undirected {
                     let g = $G::complete(i);
 
                     assert_eq!(g.order(), o);
-                    assert_eq!(g.size(), (o * (o + 1)) / 2);
+                    assert_eq!(g.size(), (o * (o + 1)) / 2 - o);
```
Comment (AlessioZanga) [inline tests/graphs/default.rs:109]: The same also for this line.

**Review by AlessioZanga — CHANGES_REQUESTED** [review]
In orde to stick with the mathematical notation, I would go for `(n * (n - 1)) / 2` and write `n - 1` as `n.saturating_sub(1)` to avoid underflow.

**Review by AlessioZanga — APPROVED** [review]
Thanks for applying the requested changes!
